[fzf-tab]
src.git = "https://github.com/Aloxaf/fzf-tab"
fetch.github = "Aloxaf/fzf-tab"

[fzf-tab-source]
src.git = "https://github.com/Freed-Wu/fzf-tab-source"
fetch.github = "Freed-Wu/fzf-tab-source"

[zsh-autosuggestions]
src.git = "https://github.com/zsh-users/zsh-autosuggestions"
fetch.github = "zsh-users/zsh-autosuggestions"

[zsh-syntax-highlighting]
src.git = "https://github.com/zsh-users/zsh-syntax-highlighting"
fetch.github = "zsh-users/zsh-syntax-highlighting"

[vscode-kdl]
src.github = "https://github.com/kdl-org/vscode-kdl"
fetch.github = "kdl-org/vscode-kdl"