# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  fzf-tab = {
    pname = "fzf-tab";
    version = "0983009f8666f11e91a2ee1f88cfdb748d14f656";
    src = fetchFromGitHub {
      owner = "Aloxaf";
      repo = "fzf-tab";
      rev = "0983009f8666f11e91a2ee1f88cfdb748d14f656";
      fetchSubmodules = false;
      sha256 = "sha256-yvPQyuK4Dw+LkwxrkWTRcw4PIf/79fW61jWbEg8Pe9Y=";
    };
    date = "2026-03-17";
  };
  fzf-tab-source = {
    pname = "fzf-tab-source";
    version = "5463698036f5e23ef275b4b55c42551879ebfab4";
    src = fetchFromGitHub {
      owner = "Freed-Wu";
      repo = "fzf-tab-source";
      rev = "5463698036f5e23ef275b4b55c42551879ebfab4";
      fetchSubmodules = false;
      sha256 = "sha256-ar025RTlDFWEnE9Ql8WBz4tiBmz1B2tsZiRI2/mVCDI=";
    };
    date = "2026-01-14";
  };
  zsh-autosuggestions = {
    pname = "zsh-autosuggestions";
    version = "85919cd1ffa7d2d5412f6d3fe437ebdbeeec4fc5";
    src = fetchFromGitHub {
      owner = "zsh-users";
      repo = "zsh-autosuggestions";
      rev = "85919cd1ffa7d2d5412f6d3fe437ebdbeeec4fc5";
      fetchSubmodules = false;
      sha256 = "sha256-KmkXgK1J6iAyb1FtF/gOa0adUnh1pgFsgQOUnNngBaE=";
    };
    date = "2025-06-24";
  };
  zsh-syntax-highlighting = {
    pname = "zsh-syntax-highlighting";
    version = "1d85c692615a25fe2293bdd44b34c217d5d2bf04";
    src = fetchFromGitHub {
      owner = "zsh-users";
      repo = "zsh-syntax-highlighting";
      rev = "1d85c692615a25fe2293bdd44b34c217d5d2bf04";
      fetchSubmodules = false;
      sha256 = "sha256-VMne38IQwqB4jwGUI2f3eEiSkT2ww7+G5ch7w+65GT0=";
    };
    date = "2026-02-08";
  };
}
